name: CI

on:
  push:
    branches:
      - secrets

env:
  NODE_VERSION: 24

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print node version
        env:
          NODE_ENV_TEST: ${{ secrets.NODE_ENV_TEST }}
        run: |
          echo "Node version de node: $NODE_VERSION"
      - name: Show Github Variables
        run: |
          echo "Repository: ${{ github.repository}}"
          echo "Ref: ${{ github.ref}}"
          echo "SHA: ${{ github.sha}}"